title: fleeting
description: but very opinionated
meta_description: "cs, philosophy, literature, humanism"

markdown: kramdown
highlighter: rouge
cover: assets/images/beach.jpg
logo: false
paginate: 15
baseurl: "/blog"
domain_name: 'https://misgivings.me/blog'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://misgivings.me/blog'
author:         'Jonathan Wong'
